export const ActionTypes = {
    SET_STUDENTS : "SET_STUDENTS",
    FETCH_STUDENT : "FETCH_STUDENT",
    FETCH_STUDENTS : "FETCH_STUDENTS",
    REMOVE_STUDENT : "REMOVE_STUDENT",
    REMOVE_FETCHED_STUDENT : "REMOVE_FETCHED_STUDENT"
};